### ISSUE TITLE
Too many "style" attributes

### ISSUE THREAD

**Issue by WilliamDarcy** [Alastrael/m2l_portable#1]
Please don't put the "style" attribute directly in the tag.
Use a CSS style sheet.

**Comment by Alastrael** [comment]
Why is it a problem ? I don't understand.

**Comment by WilliamDarcy** [comment]
Don't inline CSS attributes
Inlining CSS attributes on HTML elements (`<p style=...>`) should be avoided where possible, as this often leads to unnecessary code duplication. Further, inline CSS on HTML elements is blocked by default with Content Security Policy (CSP). 
From [https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery](url)

**Comment by Alastrael** [comment]
Oh okay ! Thanks for your help. I'll change that as soon as possible !
